# MinecraftPlugin Configuration File

# Plugin settings
plugin:
  enabled: true
  debug: false

# Testament God System Configuration
testament:
  # Fragment spawn settings
  fragments:
    chest_spawn_chance: 0.02  # 2% chance after opening 50+ chests
    mob_drop_chance: 0.001    # 0.1% chance from dangerous mobs
    chest_cooldown_hours: 2   # Hours between chest fragments
    mob_cooldown_hours: 1     # Hours between mob fragments
  
  # Ascension system settings
  ascension:
    effects_enabled: true
    level_announcements: true
  
  # Divine conflict settings
  conflicts:
    enabled: true
    remove_conflicting_items: true
    announce_conflicts: true
  
  # God-specific settings
  gods:
    fallen:
      heart_return_seconds: 45
      max_hearts: 25
    forge:
      repair_cooldown_seconds: 30
      wind_burst_damage: 8
    veil:
      nullification_range: 16
      reality_effects: true

  # Testament Lives System Configuration
  lives_system:
    # Death threshold before becoming prisoner of void
    death_threshold: 3
    
    # Void world settings
    void_world_name: "world"  # Use main world for now
    void_teleport_coords:
      x: 0
      y: -60  # Deep underground void area
      z: 0
    
    # Messages
    prisoner_message: "§c§lYou are a Prisoner of the Void. Only redemption can free you."
    redemption_broadcast: true  # Announce when someone is redeemed
    
    # Post-void restrictions
    restrict_unpledged: true  # Prevent divine item use until pledged
    vulnerable_effects: true  # Apply debuffs to unpledged players
    
    # Redemption system settings
    redemption:
      # Altar settings
      altar_material: "BEACON"  # Block type for Redemption Altar
      
      # Key creation announcements
      announce_key_creation: true
      
      # Redemption process settings
      broadcast_redemption: true
      broadcast_message: "§b§l{redeemer} §r§bhas freed §b§l{prisoner} §r§bfrom the Void!"
      
      # Teleport location for freed players
      teleport_world: "world"
      teleport_coords:
        x: 0
        y: 100
        z: 0
      
      # Redemption costs
      xp_loss_percentage: 0.5  # 50% of total XP lost
      clear_non_divine_items: false  # Whether to clear non-divine items
      reduced_max_hearts: 10  # Player will have 5 hearts (10 HP) after redemption
      cost_message: "§e§lRedemption comes with a price. Learn from this experience."

  # Tutorial System Configuration
  tutorial:
    enabled: true
    auto_start_for_new_players: true
    skip_allowed: true
    reset_allowed: true

  # Performance Optimization Configuration
  performance:
    logging:
      enabled: false  # Enable performance logging for debugging
    caching:
      enabled: true
    async_operations:
      enabled: true

  # Visual Effects Configuration
  effects:
    enabled: true
    particle_density: 1.0  # Multiplier for particle count (0.5 = half, 2.0 = double)
    sound_effects: true
    god_auras: true
    ability_effects: true
    testament_completion_effects: true
    convergence_effects: true

  # Custom Raids Configuration
  raids:
    enabled: true
    max_concurrent_raids: 10
    instance_cleanup_delay: 300  # seconds before cleaning up completed raid instances
    
    # Dynamic scaling settings
    scaling:
      enabled: true
      player_count_factor: 0.3  # 30% increase per additional player
      power_level_factor: 0.15  # 15% increase per power level
      max_scaling_multiplier: 3.0  # Maximum scaling multiplier
      
    # Leaderboard settings
    leaderboards:
      enabled: true
      max_records: 1000  # Maximum records to keep
      cleanup_interval_hours: 168  # Weekly cleanup
      
    # Weekly challenge settings
    weekly_challenges:
      enabled: true
      rotation_interval_hours: 168  # 7 days
      bonus_reward_multiplier: 1.3  # 30% bonus for weekly challenge completions
      
    rewards:
      xp_multiplier: 1.0
      item_rewards: true
      cosmetic_rewards: true
      weekly_challenge_bonus: 1.5  # 50% bonus XP for weekly challenges
      
    # Guild system settings
    guilds:
      enabled: true
      max_guild_size: 20
      min_guild_name_length: 3
      max_guild_name_length: 20
      guild_raid_bonus: 1.2  # 20% bonus for guild raids
      
      # Guild raid requirements
      min_guild_members_for_raid: 2
      guild_only_raids: false  # Whether some raids require guild membership

  # Natural Altar Generation System
  altars:
    natural_generation:
      # Enable/disable natural altar generation
      enabled: true
      
      # Base chance for altar generation per chunk (0.001 = 0.1%)
      base_spawn_chance: 0.001
      
      # Minimum distance between altars in blocks
      min_distance: 500
      
      # Maximum altars per chunk
      max_per_chunk: 1
      
      # Biome-specific spawn rate multipliers
      biome_multipliers:
        # Core god biomes get higher spawn rates
        swamp: 2.0
        dark_forest: 2.0
        deep_dark: 1.5
        desert: 2.0
        badlands: 1.5
        ocean: 1.8
        forest: 2.0
        jungle: 1.5
        mountains: 1.8
        the_end: 0.5  # Rare in End
        
        # Expansion god biomes
        dripstone_caves: 1.2
        lush_caves: 1.2
        nether: 0.8
        sculk: 1.0
      
      # God rarity weights (higher = more common)
      god_weights:
        # Core gods are more common
        fallen: 3
        banishment: 3
        abyssal: 3
        sylvan: 3
        tempest: 3
        veil: 2  # Slightly rarer
        
        # Expansion gods are rarer
        forge: 1
        void: 1
        time: 1
        blood: 1
        crystal: 1
        shadow: 1

  # Transcendence System Configuration (Post-Convergence Content)
  transcendence:
    enabled: true
    challenge_completion_effects: true
    reality_manipulation_enabled: true
    cosmic_architecture_enabled: true
    dimensional_sovereignty_enabled: true
    universal_deity_powers_enabled: true
    
    # Challenge difficulty settings
    challenges:
      auto_detection: true  # Automatically detect challenge completion
      manual_completion: false  # Allow manual completion (admin only)
      progress_tracking: true
      
    # Transcendence abilities
    abilities:
      reality_shaper:
        block_manipulation_range: 100
        matter_transmutation_enabled: true
        space_folding_distance: 50
      cosmic_architect:
        realm_creation_enabled: true
        physics_modification_enabled: true
        life_creation_enabled: true
      dimensional_sovereign:
        multiverse_access: true
        dimensional_control_range: 1000
        cosmic_governance_enabled: true
      universal_deity:
        omnipotence_level: 10
        omniscience_enabled: true
        omnipresence_enabled: true

# Divine Council Configuration (Post-Convergence Content)
divine_council:
  # WARNING: Enabling the Divine Council system will fundamentally change server dynamics!
  # 
  # IMPORTANT: It is STRONGLY RECOMMENDED to reset your world when enabling this feature
  # for the first time, as the Divine Council system introduces:
  # 
  # 1. REALITY MANIPULATION: Council members can alter terrain, spawn structures,
  #    and modify the physical world through proposals and cosmic interventions
  # 
  # 2. ECONOMIC DISRUPTION: Fragment rain events and divine blessings can
  #    dramatically alter the server economy and player progression rates
  # 
  # 3. POWER IMBALANCE: Converged players gain access to server-wide governance
  #    that can affect all other players' gameplay experience
  # 
  # 4. IRREVERSIBLE CHANGES: Some cosmic interventions create permanent world
  #    modifications that cannot be easily undone
  # 
  # 5. SAVE CORRUPTION RISK: Reality manipulation features stress the world
  #    save system and may cause corruption in existing worlds with complex builds
  # 
  # If you enable this on an existing world, BACKUP YOUR WORLD FILES FIRST!
  # Consider this a "New Game+" feature for servers ready for cosmic-level gameplay.
  enabled: false
  max_size: 12  # Maximum number of council members
  approval_threshold: 0.6  # 60% approval needed for proposals to pass
  proposal_duration_hours: 72  # How long proposals stay active
  auto_promote: true  # Automatically promote members based on activity
  
  # Council powers and abilities
  powers:
    server_events: true  # Can trigger server-wide events
    rule_enforcement: true  # Can enforce server rules
    cosmic_intervention: true  # Can perform cosmic interventions
    member_management: true  # Can manage council membership
    proposal_execution: true  # Enable automatic proposal execution
    reality_manipulation: true  # Can alter world terrain and structures
    economic_control: true  # Can affect server economy and progression
    player_governance: true  # Can make decisions affecting all players
    dimensional_access: true  # Can access and modify other dimensions
    
  # Proposal settings
  proposals:
    max_active: 5  # Maximum active proposals at once
    min_description_length: 20  # Minimum characters for proposal description
    require_unanimous_for_critical: true  # Critical proposals need unanimous approval
    auto_execute: true  # Automatically execute passed proposals
    execution_delay_seconds: 30  # Delay before executing passed proposals
    reality_proposals_enabled: true  # Allow reality manipulation proposals
    economic_proposals_enabled: true  # Allow economic intervention proposals
    punishment_proposals_enabled: true  # Allow divine punishment proposals
    world_event_proposals_enabled: true  # Allow world-altering event proposals
    
  # Notification settings
  notifications:
    announce_new_members: true
    announce_proposals: true
    announce_results: true
    notify_offline_members: true
    announce_executions: true  # Announce when proposals are executed
    reality_change_warnings: true  # Warn players before reality changes
    economic_change_alerts: true  # Alert players to economic changes
    
  # Event settings for proposal execution
  events:
    fragment_rain:
      duration_minutes: 10
      rate_multiplier: 10.0
      particle_effects: true
      max_fragments_per_player: 5  # Limit to prevent economy breaking
    divine_blessing:
      duration_minutes: 30
      effect_strength: 2
      apply_to_new_players: true
      health_bonus_hearts: 5  # Temporary health bonus
    cosmic_storm:
      duration_minutes: 15
      effect_frequency_seconds: 10
      reality_distortion: true
      terrain_modification: false  # Disable terrain changes by default
    altar_manifestation:
      max_altars: 7
      min_distance: 100
      notification_radius: 100
      biome_restrictions: true  # Respect biome compatibility
    reality_reset:
      enabled: false  # Extremely dangerous - can corrupt worlds
      backup_required: true  # Force backup before execution
      confirmation_required: true  # Require additional confirmation
    divine_punishment:
      max_duration_hours: 24  # Maximum punishment duration
      reversible: true  # Punishments can be reversed
      appeal_system: true  # Allow appeals through council
    cosmic_balance:
      affect_all_players: true  # Apply to all online players
      reset_negative_effects: true  # Clear debuffs
      normalize_stats: false  # Don't reset player progression
      
  # Integration settings
  integration:
    raids:
      council_raids_enabled: true  # Enable special council raids
      convergence_raid_access: true  # Council can trigger convergence raids
      raid_difficulty_control: true  # Council can adjust raid difficulty
    events:
      seasonal_events: true  # Council can trigger seasonal events
      custom_events: true  # Council can create custom events
      world_events: true  # Council can trigger world-wide events
    economy:
      fragment_market_control: true  # Council can affect fragment economy
      divine_item_regulation: true  # Council can regulate divine items
      progression_control: true  # Council can affect player progression
    governance:
      rule_creation: true  # Council can create new server rules
      punishment_system: true  # Council can punish rule violations
      appeal_system: true  # Players can appeal council decisions
      democratic_voting: true  # All decisions require council vote
      
  # Safety and backup settings
  safety:
    auto_backup_before_reality_changes: true  # Backup world before major changes
    max_reality_changes_per_day: 3  # Limit reality-altering proposals
    require_admin_approval_for_critical: true  # Admin must approve critical proposals
    emergency_stop_enabled: true  # Allow emergency stopping of proposals
    rollback_capability: true  # Enable rollback of recent changes
    world_corruption_protection: true  # Extra protection against corruption

# Example configuration options
example:
  welcome-message: "Welcome to our server!"
  join-broadcast: true
  quit-broadcast: true

# You can add more configuration options here