# Database Configuration for Testament System

database:
  # Enable database storage (MySQL)
  enabled: false
  
  # Database connection settings
  url: "jdbc:mysql://localhost:3306/testament"
  username: "testament"
  password: "password"
  
  # Connection pool settings
  pool:
    max_size: 10
    min_idle: 2
    connection_timeout: 30000  # 30 seconds
    idle_timeout: 600000       # 10 minutes
    max_lifetime: 1800000      # 30 minutes
  
  # Migration settings
  migrations:
    enabled: true
    auto_run: true
    backup_before_migration: true
  
  # Backup settings
  backup:
    enabled: true
    interval_hours: 24
    retention_days: 7
    location: "backups/database"
  
  # Cross-server settings
  cross_server:
    enabled: false
    sync_interval_minutes: 5
    server_heartbeat_minutes: 1
    offline_timeout_minutes: 5
  
  # Performance settings
  performance:
    batch_size: 100
    query_timeout_seconds: 30
    connection_validation: true
    cache_prepared_statements: true