name: ChroniclesOfThePantheon
version: '1.21.8'
main: com.example.minecraftplugin.MinecraftPlugin
api-version: '1.21'
authors: [ YourName ]
description: Chronicles of the Pantheon - A Minecraft plugin for version 1.21.8
website: https://example.com

commands:
  example:
    description: Example command
    usage: /<command>
    permission: minecraftplugin.example
    permission-message: You don't have permission to use this command!
  testament:
    description: View your testament progress and fragment collection
    usage: /<command> [status|fragments [god]|lives|admin]
    permission: minecraftplugin.testament
    permission-message: You don't have permission to use this command!
  godlex:
    description: View detailed information and lore about the gods
    usage: /<command> [god_name]
    permission: minecraftplugin.godlex
    permission-message: You don't have permission to use this command!
  altar:
    description: Manage natural altar generation
    usage: /<command> [generate|stats|reload|clear]
    permission: minecraftplugin.altar
    permission-message: You don't have permission to use this command!
  tutorial:
    description: Access the Testament System tutorial
    usage: /<command> [start|skip|reset|progress|status]
    permission: minecraftplugin.tutorial
    permission-message: You don't have permission to use this command!
  raid:
    description: Manage and participate in custom raids
    usage: /<command> [list|info|start|leave|status|stats]
    permission: minecraftplugin.raid
    permission-message: You don't have permission to use this command!
  config:
    description: Advanced configuration management
    usage: /<command> [reload|get|set|template|export|import|stats|validate]
    permission: minecraftplugin.admin
    permission-message: You don't have permission to use this command!
  transcendence:
    description: Access transcendence content beyond Divine Convergence
    usage: /<command> [status|challenges|abilities|help]
    permission: minecraftplugin.transcendence
    permission-message: You don't have permission to use this command!
  council:
    description: Access the Divine Council system for converged players
    usage: /<command> [status|join|leave|members|propose|vote|proposals|help]
    permission: minecraftplugin.council
    permission-message: You don't have permission to use this command!
  bounty:
    description: Manage bounties on other players
    usage: /<command> [place|check|list|remove|stats]
    permission: minecraftplugin.bounty
    permission-message: You don't have permission to use this command!
  guild:
    description: Manage raid guilds and team formation
    usage: /<command> [create|invite|join|leave|info|list|help]
    permission: minecraftplugin.guild
    permission-message: You don't have permission to use this command!
  forge:
    description: Access the Divine Forge for upgrading and combining divine items
    usage: /<command> [upgrade|combine|info|materials|combinations|help]
    permission: minecraftplugin.forge
    permission-message: You don't have permission to use this command!

permissions:
  minecraftplugin.example:
    description: Allows use of the example command
    default: true
  minecraftplugin.testament:
    description: Allows use of the testament command
    default: true
  minecraftplugin.godlex:
    description: Allows use of the godlex command
    default: true
  minecraftplugin.altar:
    description: Allows use of the altar command
    default: op
  minecraftplugin.tutorial:
    description: Allows use of the tutorial command
    default: true
  minecraftplugin.raid:
    description: Allows use of the raid command
    default: true
  minecraftplugin.config:
    description: Allows use of the config command
    default: op
  minecraftplugin.transcendence:
    description: Allows use of the transcendence command
    default: true
  minecraftplugin.council:
    description: Allows use of the council command
    default: true
  minecraftplugin.bounty:
    description: Allows use of the bounty command
    default: true
  minecraftplugin.guild:
    description: Allows use of the guild command
    default: true
  minecraftplugin.forge:
    description: Allows use of the forge command
    default: true
  minecraftplugin.admin:
    description: Allows use of admin commands
    default: op
  minecraftplugin.admin.critical:
    description: Allows execution of critical Divine Council proposals
    default: op